site_name: Azurite
site_url:
repo_url: https://github.com/Red-C0der/Azurite
repo_name: GitHub
site_author: Red_C0der
copyright: © Red_C0der 2015/16

theme: flatly

pages:
- Home: index.md
- Documentation:
    - 'Installation': 'installation.md'
    - 'Setup': 'setup.md'
    - 'Use Azurite': 'usage.md'
    - 'Azurite Script': 'azurite-script.md'
    - 'API - Implementation': 'api-implementation.md'
- About:
    - 'Contact': 'contact.md'
    - 'License': 'license.md'